### PR TITLE
update ruby version to 2.3.0

### PR DESCRIPTION
**Pull request by ywjno**

### CODE REVIEW

**Comment by cheunghy** [comment]
👍

**Comment by dongli** [comment]
Thanks for contribution! I will give it a shot later~

**Comment by ywjno** [comment]
Just update `setup.sh` uesd ruby version, packages not updated yet

**Comment by dongli** [comment]
@ywjno Just found it~, I will try to update the Ruby package too.

**Comment by dongli** [comment]
I need to solve a problem before updating Ruby package version:

The installed gems by the previous Ruby version may need to be isolated, since I have linked them into a common directory (see `packman.active`).

**Pull request merged**
