### PR TITLE
Add package kroman

### PR DESCRIPTION
**Pull request by cheunghy**
kroman is a Korean hangul to Romanized syllables converter.
😀

Also, I encountered a issue

This happens when packman is configuring and creating `packman.config`. Hope it helps! 😀
```
localhost:Desktop 1$ ~/Documents/Project/packman/packman install kroman
/Users/1/Documents/Project/packman/framework/config_manager.rb:146:in `block in template': undefined method `os_spec' for PACKMAN:Module (NoMethodError)
	from /Users/1/Documents/Project/packman/framework/config_manager.rb:132:in `open'
	from /Users/1/Documents/Project/packman/framework/config_manager.rb:132:in `template'
	from /Users/1/Documents/Project/packman/framework/command_line.rb:102:in `init'
	from /Users/1/Documents/Project/packman/framework/packman_framework.rb:103:in `<top (required)>'
	from /Users/1/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/1/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/1/Documents/Project/packman/packman:12:in `<main>'
```

### CODE REVIEW

**Comment by dongli** [comment]
Hi, @cheunghy ! I will try it, and fix the bug you have encountered. Thanks for your contribution!

**Comment by dongli** [comment]
@cheunghy I have modified your version with the following one, check this out:
```Ruby
class Kroman < PACKMAN::Package
  url 'https://github.com/cheunghy/kroman/archive/v1.0.tar.gz'
  sha1 'f3a9341c4c5b68ed8183a94d00875e41c81c395b'
  version '1.0'
  filename 'kroman-1.0.tar.gz'

  label :compiler_insensitive

  def install
    PACKMAN.run "make install PREFIX=#{prefix}"
  end
end
```

**Comment by cheunghy** [comment]
It works fine! packman is very nice tool!

**Comment by cheunghy** [comment]
👍

**Pull request merged**
