### PR TITLE
Added support for fish shell

### PR DESCRIPTION
**Pull request by liruizhe**
Hello, I have added support for fish shell, which includes setup and auto-completion.
I have tested it on Mac OS X El Capitan and CentOS 6.7 (both of them are using fish version 2.2.0).

### CODE REVIEW

**Comment by dongli** [comment]
Thanks @liruizhe for your work!

**Comment by dongli** [comment]
I found a problem about `setup.sh`. `$SHELL` will be always `/bin/bash`, so the branch `[[ "$SHELL" =~ "fish" ]]` will not be executed in `setup.sh`.

**Comment by liruizhe** [comment]
@dongli $SHELL is used to store the path to your default shell. 
So you may use chsh or modify /etc/passwd to change your default shell, which affect $SHELL.

**Comment by dongli** [comment]
OK, I understood~

**Pull request merged**
